/**
 * Created by Administrator on 2018/3/15.
 */
export const ACTIONS_DEL_SHOPPINGCAR = 'DFLSAFJLJAFLFAKJFLKJ'
export const ACTIONS_ADD_SHOPPINGCAR = 'EWQREEWQRQWRWQR'
export const MUTATIONS_DEL_SHOPPINGCAR = 'YTURYURYURY'
export const MUTATIONS_ADD_SHOPPINGCAR = 'XCVBCXVBXVB'
